market/chipi/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cats/<int:cat_id>/', views.catg, name='cats_id'),
    path('product/<int:product_id>/', views.show_product, name='product'),
    path('c/<slug:category_slug>/', views.show_category, name='category'),
    path('shop/<int:seller_id>/', views.show_shop, name='shop'),
    path('addprod/', views.addprod, name='addprod'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('cart-add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart-delete/<int:cart_id>/', views.cart_delete, name='cart_delete'),
    path('cart-decr/<int:cart_id>/', views.cart_decr, name='cart_decr'),
    path('cart/', views.show_cart, name='cart'),
    path('create_order/', views.create_order, name='create_order'),
    path('pay_order/', views.pay_order, name='pay_order'),
    path('cart-decr-index/<int:product_id>/', views.cart_decr_in_index, name='cart_decr_in_index'),
    path('add-fav/<int:product_id>/', views.add_fav, name='add_fav'),
    path('rem-fav/<int:product_id>/', views.rem_fav, name='rem_fav'),
    path('favorites/', views.show_favorites, name='favorites'),
    path('cart-add-ajax/', views.cart_add_ajax, name='cart_add_ajax'),
    # path('cart-add-ajax1/', views.cart_add_ajax, name='cart_add_ajax1'),
    path('cart-decr-index_ajax/', views.cart_decr_in_index_ajax, name='cart_decr_in_index_ajax'),
    path('orders/', views.show_orders, name='orders'),
    path('orders_shop/', views.show_orders_for_shop, name='orders_shop'),
    path('', views.index, name='home'),
    path('s/', views.search, name='search'),
    path('rem_review/<int:rev_id>/', views.rem_review, name='rem_review'),
    path('edit_order/<int:order_id>/', views.edit_order, name='edit_order'),
    path('help/', views.help_page, name='help'),
    path('support/', views.support_page, name='support'),
    path('ord/<int:ord_id>/', views.show_order, name='show_order'),


]

market/market/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from chipi import views
from chipi.views import page_not_found
from market import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chipi.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found

market/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    # path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile/', views.profile, name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('shop-register/', views.RegisterShop.as_view(), name='shop_register'),
    path('edit_shop/', views.edit_shop, name='edit_shop'),
    path('address/', views.address, name='address')
]

market/templates/base.html
{% load static %}
{% load get_cart %}


{% load mptt_tags %}
{% load chipi_tags %}


<!--&gt;>>>>>> temp_branch-->

<!DOCTYPE html>
<html lang="ru">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chipi-Chipi</title>


<!--    <link rel="stylesheet" href="style-head.css">-->

<link rel="stylesheet" href="{% static 'chipi/css/style.css' %}">
	{% if user.is_buyer %}
	{% get_cart filter=user.pk as cart %}
	<div class="cart-icon">
        <p class="cart-icon-p"><span id="prod-cart-count">{{ cart }}</span></p>
    </div>
	{% endif %}
<div class="header">
</div>
<div class="header-line2">
	<img class="header-line1-img1" src="{% static 'chipi/images/Union.png' %}" alt="Не отобразилось">
	<a href="{% url 'home' %}" class="header-line1-p1">Chipi-Chipi</a>
	<form action="{% url 'search' %}" method="get">
		<input class='header-line1-input' class="search" type="text" name="q" placeholder="Поиск по сайту..."
			value="{{ search_text }}">
	</form>
	<!--                <input  type="text" " name="header-line1-poisk">-->
	<button class='header-line1-btn1' type="submit">
		<img class="header-line1-img2" src="{% static 'chipi/images/search_magnifier_icon_145939.png' %}" alt="Лупа">
	</button>
	{% if user.is_authenticated %}
	{% if user.is_buyer %}
	<a href="{% url 'cart' %}">
		<img class='header-line1-img3' src="{% static 'chipi/images/ShoppingCartSimple.png' %}" alt="image">
	</a>

	<a href="{% url 'favorites' %}">
		<img class='header-line1-img4' src="{% static 'chipi/images/Heart.png' %}" alt="image">
	</a>
	{% endif %}
	{% if user.is_buyer %}
	<a href="{% url 'users:profile' %}">
		<img class="header-line1-img4" src="{% static 'chipi/images/User.png' %}" alt="imagr">
	</a>
	{% else %}
	<a href="{% url 'users:edit_shop' %}">
		<img class="header-line1-img4" src="{% static 'chipi/images/User.png' %}" alt="imagr">
	</a>
	{% endif %}
	<a href="{% url 'users:logout' %}">
		<img class="header-line1-img4" src="{% static 'chipi/images/logout.svg' %}" alt="imagr">
	</a>
	{% else %}
	<a href="{% url 'users:login' %}">
		<img class="header-line1-img4" src="{% static 'chipi/images/logout.svg' %}" alt="imagr">
	</a>
	{% endif %}

</div>
<div class="header-line3">
	 <div class="filter">
                <button class="header-line3-new">
                    <p class="header-line3-p">Все категории</p>
                    <img class="header-line3-new-img" src="{% static 'chipi/images/Vector.png' %}" alt="">
                </button>
                <div class="category">
					{% get_category as ctg %}
    				{% recursetree ctg %}
					<a href="{% url 'category' category_slug=node.slug %}"><p class="category-p">{{ node.name }}</p></a>
    				{% endrecursetree %}

                </div>
            </div>
	{% if user.is_authenticated %}
	<img class='header-line3-img1' src="{% static 'chipi/images/MapPinLine.png' %}" alt="image">
	<a class="header-line3-a1" href="{% url 'orders' %}">Отследить заказ</a>
	{% else %}
	<img class='header-line3-img1' src="{% static 'chipi/images/MapPinLine.png' %}" alt="image">
	<a class="header-line3-a1" href="{% url 'users:login' %}">Отследить заказ</a>
	{% endif %}
	<img class='header-line3-img2' src="{% static 'chipi/images/Vector1.png' %}" alt="image">
	<a class="header-line3-a2" href="{% url 'support' %}">Поддержка</a>
	<img class='header-line3-img3' src="{% static 'chipi/images/Info.png' %}" alt="image">
	<a class="header-line3-a3" href="{% url 'help' %}">Нужна помощь</a>
	<img class='header-line3-img4' src="{% static 'chipi/images/PhoneCall.png' %}" alt="image">
	<a class="header-line3-a4" href="#">+79990009900</a>
</div>
<!--=======-->
<!--    <div>-->
<!--    <h2><a href="{% url 'home' %}">CHIPI-CHIPI</a></h2>-->
<!-- {% if user.is_authenticated %}-->
<!--        {% if user.is_buyer %}-->
<!--        <p>Profile: <a href="{% url 'users:profile' %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">logout</a></p>-->
<!--        {% elif user.is_shop %}-->
<!--        <p>Shop: <a href="{% url 'shop' seller_id=user.shop.id %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">logout</a></p>-->
<!--        <p><a href="{% url 'addprod' %}">Add product</a></p>-->
<!--        {% endif %}-->
<!--    {% else %}-->
<!--        <p><a href="{% url 'users:login' %}">login</a> <a href="{% url 'users:register' %}">register</a></p>-->
<!--    {% endif %} -->

<!--        {% if user.is_buyer %}-->
<!--        {% get_cart filter=user.pk as cart %}-->
<!--            {% if cart|add:0 > 0 %}-->
<!--                 <a href="{% url 'cart' %}"><p>Cart: <span id="prod-cart-count">{{ cart }}</span></p></a>-->
<!--            {% else %}-->
<!--        <a href="{% url 'cart' %}"><p>Cart: <span id="prod-cart-count">0</span></p></a>-->
<!--            {% endif %}-->
<!--        {% else %}-->
<!--        <p>Cart: empty</p>-->
<!--        {% endif %}-->
<!--        <a href="{% url 'favorites' %}">Favorites</a>-->
<!--        {% if user.is_authenticated %}-->
<!--            {% if user.is_buyer %}-->
<!--                <a href="{% url 'orders' %}">Orders</a>-->
<!--            {% elif user.is_shop %}-->
<!--                <a href="{% url 'orders_shop' %}">Shop orders</a>-->
<!--            {% endif %}-->
<!--        {% endif %}-->
<!--        <form action="{% url 'search' %}" method="get">-->
<!--            <input class="search" type="text" name="q" placeholder="Search.." value="{{ search_text }}">-->
<!--        </form>-->





<!--        <p>{% get_category as ctg %}</p>-->
<!--        <ul class="root">-->
<!--&lt;!&ndash;            {{ ctg }}&ndash;&gt;-->
<!--    {% recursetree ctg %}-->
<!--        <li>-->
<!--            <a href="{% url 'category' category_slug=node.slug %}">{{ node.name }}</a>-->
<!--            {% if not node.is_leaf_node %}-->
<!--                <ul class="children">-->
<!--                    {{ children }}-->
<!--                </ul>-->
<!--            {% endif %}-->
<!--        </li>-->
<!--    {% endrecursetree %}-->
<!--</ul>-->
<!--&gt;>>>>>> temp_branch-->



<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>CHIPI-CHIPI</title>-->
<!--    <link rel="stylesheet" href="{% static 'chipi/css/style.css' %}">-->
<!--</head>-->
<!--<body>-->
<!--    <div>-->
<!--    <h2><a href="{% url 'home' %}">CHIPI-CHIPI</a></h2>-->
<!--    {% if user.is_authenticated %}-->
<!--        {% if user.is_buyer %}-->
<!--        <p>Profile: <a href="{% url 'users:profile' %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">logout</a></p>-->
<!--        {% elif user.is_shop %}-->
<!--        <p>Shop: <a href="{% url 'shop' seller_id=user.shop.id %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">logout</a></p>-->
<!--        <p><a href="{% url 'addprod' %}">Add product</a></p>-->
<!--        {% endif %}-->
<!--    {% else %}-->
<!--        <p><a href="{% url 'users:login' %}">login</a> <a href="{% url 'users:register' %}">register</a></p>-->
<!--    {% endif %}-->

<!--        {% if user.is_buyer %}-->
<!--        {% get_cart filter=user.pk as cart %}-->
<!--            {% if cart|add:0 > 0 %}-->
<!--                 <a href="{% url 'cart' %}"><p>Cart: <span id="prod-cart-count">{{ cart }}</span></p></a>-->
<!--            {% else %}-->
<!--        <a href="{% url 'cart' %}"><p>Cart: <span id="prod-cart-count">0</span></p></a>-->
<!--            {% endif %}-->
<!--        {% else %}-->
<!--        <p>Cart: empty</p>-->
<!--        {% endif %}-->
<!--        <a href="{% url 'favorites' %}">Favorites</a>-->
<!--        <a href="{% url 'orders' %}">Orders</a>-->
<!--=======-->
<!--        {% if user.is_buyer %}-->
<!--        {% get_cart filter=user.pk as cart %}-->
<!--            {% if cart|add:0 > 0 %}-->
<!--                 <a href="{% url 'cart' %}"><p>Cart: <span id="prod-cart-count">{{ cart }}</span></p></a>-->
<!--            {% else %}-->
<!--        <a href="{% url 'cart' %}"><p>Cart: <span id="prod-cart-count">0</span></p></a>-->
<!--            {% endif %}-->
<!--        {% else %}-->
<!--        <p>Cart: empty</p>-->
<!--        {% endif %}-->
<!--        <a href="{% url 'favorites' %}">Favorites</a>-->
<!--        <a href="{% url 'orders' %}">Orders</a>-->
<!--        <form action="{% url 'search' %}" method="get">-->
<!--            <input class="search" type="text" name="q" placeholder="Search.." value="{{ search_text }}">-->
<!--        </form>-->




<!--        <p>{% get_category as ctg %}</p>-->
<!--        <ul class="root">-->
<!--&lt;!&ndash;            {{ ctg }}&ndash;&gt;-->
<!--    {% recursetree ctg %}-->
<!--        <li>-->
<!--            <a href="{% url 'category' category_slug=node.slug %}">{{ node.name }}</a>-->
<!--            {% if not node.is_leaf_node %}-->
<!--                <ul class="children">-->
<!--                    {{ children }}-->
<!--                </ul>-->
<!--            {% endif %}-->
<!--        </li>-->
<!--    {% endrecursetree %}-->
<!--</ul>-->
<!--&gt;>>>>>> temp_branch-->



<!--    </div>-->
<!--    <hr><hr>-->
{% block content %} {% endblock %}


<div class="bottom">
	<div class="bottom1">
		<div class="bottom1-line1">
			<img class="bottom1-img1" src="{% static 'chipi/images/Union1.png' %}" alt="">
			<a href="index-head.html">
				<p class="bottom1-p1">Chipi-Chipi</p>
			</a>
		</div>
		<p class="bottom1-p2">Поддержка клиентов:</p>
		<a href="#">
			<p class="bottom1-p3">Номера нет</p>
		</a>
		<a href="#">
			<p class="bottom1-p3">Адреса нет</p>
		</a>
		<a href="#">
			<p class="bottom1-p3">Почты нет</p>
		</a>
	</div>
	<div class="bottom2">
		<p class="bottom2-p1">Категории</p>
		<a href="#">
			<p class="bottom2-p2">Компьютеры и ноутбуки</p>
		</a>
		<a href="#">
			<p class="bottom2-p2">Телефоны</p>
		</a>
		<a href="#">
			<p class="bottom2-p2">Наушники</p>
		</a>
		<a href="#">
			<p class="bottom2-p2">Камера и фото</p>
		</a>
		<a href="#">
			<p class="bottom2-p2">TV и дом</p>
		</a>
		<a href="#">
			<div class="bottom2-vse-tovary">
				<p class="bottom2-p7">Посмотреть все товары</p>
				<img class="bottom2-img1" src="{% static 'chipi/images/ArrowRight3.png' %}" alt="">
			</div>
		</a>
	</div>
	<div class="bottom2">
		<p class="bottom2-p1">Полезные ссылки</p>
		<a href="#">
			<p class="bottom2-p2">Товары магазина</p>
		</a>
		<a href="#">
			<p class="bottom2-p2">Корзина</p>
		</a>
		<a href="#">
			<p class="bottom2-p2">Список желаний</p>
		</a>
		<a href="#">
			<p class="bottom2-p2">Сравнить</p>
		</a>
		<a href="index-zakaz.html">
			<p class="bottom2-p2">Отследить доставку</p>
		</a>
		<a href="index-podderzhka.html">
			<p class="bottom2-p2">Пользовательская поддержка</p>
		</a>
	</div>
</div>
<script src="{% static 'chipi/js/jquery/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'chipi/js/jquery-ajax.js' %}"></script>
<script src="{% static 'chipi/js/head.js' %}"></script>
</body>

</html>