market/chipi/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cats/<int:cat_id>/', views.catg, name='cats_id'),
    path('product/<int:product_id>/', views.show_product, name='product'),
    path('c/<slug:category_slug>/', views.show_category, name='category'),
    path('shop/<int:seller_id>/', views.show_shop, name='shop'),
    path('addprod/', views.addprod, name='addprod'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('cart-add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart-delete/<int:cart_id>/', views.cart_delete, name='cart_delete'),
    path('cart-decr/<int:cart_id>/', views.cart_decr, name='cart_decr'),
    path('cart/', views.show_cart, name='cart'),
    path('create_order/', views.create_order, name='create_order'),
    path('pay_order/', views.pay_order, name='pay_order'),
    path('cart-decr-index/<int:product_id>/', views.cart_decr_in_index, name='cart_decr_in_index'),
    path('add-fav/<int:product_id>/', views.add_fav, name='add_fav'),
    path('rem-fav/<int:product_id>/', views.rem_fav, name='rem_fav'),
    path('favorites/', views.show_favorites, name='favorites'),
    path('cart-add-ajax/', views.cart_add_ajax, name='cart_add_ajax'),
    # path('cart-add-ajax1/', views.cart_add_ajax, name='cart_add_ajax1'),
    path('cart-decr-index_ajax/', views.cart_decr_in_index_ajax, name='cart_decr_in_index_ajax'),
    path('orders/', views.show_orders, name='orders'),
    path('orders_shop/', views.show_orders_for_shop, name='orders_shop'),
    path('', views.index, name='home'),
    path('s/', views.search, name='search'),
    path('rem_review/<int:rev_id>/', views.rem_review, name='rem_review'),
    path('edit_order/<int:order_id>/', views.edit_order, name='edit_order'),
    path('help/', views.help_page, name='help'),
    path('support/', views.support_page, name='support'),
    path('ord/<int:ord_id>/', views.show_order, name='show_order'),


]

market/market/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from chipi import views
from chipi.views import page_not_found
from market import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chipi.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found

market/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    # path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile/', views.profile, name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('shop-register/', views.RegisterShop.as_view(), name='shop_register'),
    path('edit_shop/', views.edit_shop, name='edit_shop'),
    path('address/', views.address, name='address')
]

market/chipi/models.py
import os

from django.db import models
from django.urls import reverse
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from users.models import User, Buyer


# from users.models import User
# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    count = models.PositiveIntegerField(default=0)
    # category = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='products', blank=True)
    prodcategory = models.ForeignKey('ProdCategory', on_delete=models.PROTECT, related_name='products', null=True)
    shop = models.ForeignKey('Shop', on_delete=models.PROTECT, related_name='products')
    time_created = models.DateTimeField(auto_now_add=True)
    time_updated = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    logo_image = models.ImageField(upload_to='logos/')

    def get_absolute_url(self):
        return reverse('product', kwargs={'product_id': self.pk})

    def save(self, *args, **kwargs):
        try:
            this = Product.objects.get(id=self.id)
            if this.logo_image != self.logo_image:
                if os.path.isfile(this.logo_image.path):
                    os.remove(this.logo_image.path)
        except:
            pass

        super(Product, self).save(*args, **kwargs)

    # def __str__(self):
    #     return self.title

    class Meta:
        ordering = ["pk"]


class ProductImage(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='photos/')


class ProdCategory(MPTTModel):
    name = models.CharField(max_length=50, unique=True, verbose_name='Название')
    parent = TreeForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, related_name='children',
                            db_index=True, verbose_name='Родительская категория')
    slug = models.SlugField(max_length=63, unique=True, db_index=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        unique_together = [['parent', 'slug']]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    # def get_absolute_url(self):
    #     return reverse('post-by-category', args=[str(self.slug)])

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.name



class Shop(models.Model):
    '''- id
        - seller_id
        - name
        - (Rating)
        - (Sklad address)'''
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, related_name='shop', null=True)
    name = models.CharField(max_length=63, db_index=True)
    email = models.EmailField(blank=True, unique=True, null=True)
    phone = models.CharField(blank=True, null=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop', kwargs={'seller_id': self.pk})

    class Meta:
        ordering = ["pk"]


class Review(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='reviews')
    # from_user = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(Buyer, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField(blank=True)
    time_created = models.DateTimeField(auto_now_add=True)
    score = models.PositiveIntegerField()
    image = models.ImageField(upload_to='reviews/', blank=True)


class Cart(models.Model):
    user = models.ForeignKey(Buyer, on_delete=models.CASCADE, related_name='cart')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='cart')
    count = models.PositiveIntegerField(default=1)
    time_created = models.DateTimeField(auto_now_add=True)
    time_updated = models.DateTimeField(auto_now=True)

    def sum(self):
        return self.count * self.product.price


class Favorite(models.Model):
    user = models.ForeignKey(Buyer, on_delete=models.CASCADE, related_name='favorite')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='favorite')
    time_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-time_created"]


class Order(models.Model):
    class Status(models.IntegerChoices):
        CREATED = 0, 'Создан'
        PAID_FOR = 1, 'Оплачен'
        ASSEMBLING = 2, 'В сборке'
        TRANSIT = 3, 'В пути'
        WAITING = 4, 'Ожидает выдачи'
        DELIVERED = 5, 'Доставлен'
        CANCELED = 10, 'Отменен'
    '''+ address'''
    user = models.ForeignKey(Buyer, on_delete=models.CASCADE, related_name='orders')
    shop = models.ForeignKey(Shop, on_delete=models.SET_NULL, related_name='orders', null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name='orders', null=True)
    count = models.PositiveIntegerField()
    price = models.PositiveBigIntegerField()
    time_created = models.DateTimeField(auto_now_add=True)
    time_updated = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=Status.choices, default=Status.PAID_FOR)
    title = models.CharField(max_length=255)
    track = models.CharField(blank=True)

    first_name = models.CharField(max_length=63)
    middle_name = models.CharField(max_length=63, blank=True)
    last_name = models.CharField(max_length=63)
    email = models.EmailField()
    phone = models.CharField()
    country = models.CharField()
    region = models.CharField()
    city = models.CharField()
    index = models.CharField()
    addr = models.CharField()

market/chipi/forms.py
from django import forms
from .models import Product, Category, Shop, ProductImage, Review, Order


# class AddProdForm(forms.Form):
#     title = forms.CharField(max_length=255, label='Название')
#     # slug = forms.SlugField()
#     price = forms.IntegerField(label='Цена')
#     count = forms.IntegerField(label='Количество')
#     description = forms.CharField(widget=forms.Textarea, required=False, label='Описание')
#     is_published = forms.BooleanField(required=False, initial=True)
#     category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Категория не выбрана', label='Категория')
#     shop = forms.ModelChoiceField(queryset=Shop.objects.all(), empty_label='Выберите продавца', label='Продавец')
#

class AddProdForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'name-input'}))
    price = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'price-input'}))
    count = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'kolvo-input'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'opisanie-input'}))
    # prodcategory = forms.MultipleChoiceField()
    # logo_image = forms.ImageField(widget=forms.FileInput(attrs={'class': ''}))
    class Meta:
        model = Product
        fields = ['title', 'price', 'count', 'description', 'prodcategory', 'logo_image']
        labels = {
            'title': 'Название',
            'price': 'Цена',
            'count': 'Количество в наличии',
            'description': 'Описание',
            'prodcategory': 'Категория',
            'logo_image': 'Аватарка',
        }

    def clean_price(self):
        price = self.cleaned_data['price']
        if price < 1:
            raise forms.ValidationError('Цена не может быть меньше 1 рубля')
        return price

    def clean_count(self):
        count = self.cleaned_data['count']
        if count < 0:
            raise forms.ValidationError('Количество не может быть отрицательным')
        return count

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 3:
            raise forms.ValidationError('Слишком короткое название')
        return title


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = ProductImage
        fields = ('image', )


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'score', 'image',]
        labels = {
            'text': 'Текст отзыва',
            'score': 'Оценка',
            'image': 'Изображение',
        }

    def clean_score(self):
        score = self.cleaned_data['score']
        if score not in [1,2,3,4,5]:
            raise forms.ValidationError('Оценка должна быть от 1 до 5')
        return score


class EditOrderForm(forms.ModelForm):
    track = forms.CharField(widget=forms.TextInput(attrs={'class': 'treck-input'}))
    class Meta:
        model = Order
        fields = ['status', 'track']
        labels = {
            'status': 'Статус',
            'track': 'Трек-номер',
        }

market/chipi/templates/chipi/addprod.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'chipi/css/addprod.css' %}">


<form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
    <p class="upp">Добавление товара</p>
     <div class="account-p" style="color: #FF4242;">
			{{ form.non_field_errors }}
		</div>
        <div class="uppload">
            <div class="uppload1">
                <div class="name">
                    <p class="name-p">Название</p>
<!--                    <textarea class="name-input" name="opisanie"></textarea>-->
                    {{ form.title }}
                    <p class="name-p">{{ p.title.errors }}</p>
                </div>
                <div class="price">
                    <p class="price-p">Цена</p>
<!--                    <input class="price-input" type="number">-->
                    {{ form.price }}
                    <p class="price-p">{{ form.price.errors }}</p>
                </div>
            </div>
            <div class="uppload1">
                <div class="opisanie">
                    <p class="opisanie-p">Описание</p>
<!--                    <textarea class="opisanie-input" name="opisanie"></textarea>-->
                        {{ form.description }}
                    <p class="opisanie-p">{{ form.description.errors }}</p>
                </div>
                <div class="kolvo">
                    <p class="kolvo-p">Количество в наличии</p>
<!--                    <input class="kolvo-input" type="number">-->
                    {{ form.count }}
                    <p class="kolvo-p">{{ form.count.errors }}</p>
                </div>
            </div>
            <div class="uppload1">
                <div class="kategory">
                    <p class="kategory-p">Категории</p>
                    {{ form.prodcategory }}
                    <p class="kategory-p">{{ form.prodcategory.errors }}</p>
                </div>
            </div>
            <div class="uppload1">
                <div class="ava">
                    <p class="ava-p">Изображение</p>
<!--                    <input type="file">-->
                    {{ form.logo_image }}
                    <p class="kategory-p">{{ form.logo_image.errors }}</p>
                </div>
            </div>
            <div class="uppload1">
                <div class="foto">
                    <p class="foto-p">Фото</p>
                    <input type="file" name = "files" multiple accept="image/*" />
                </div>
            </div>
            <div class="uppload2">
                <button class="uppload-btn" type="submit">
                    <p class="uppload-p">ДОБАВИТЬ</p>
                </button>
            </div>
        </div>
</form>

{% endblock %}

market/chipi/templates/chipi/favorites.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'chipi/css/style-favorite.css' %}">

    {% if user.is_buyer and prod %}




<div>
        <link rel="stylesheet" href="style-favorite.css">

                <div class="container">
                    <h2>Список желаемого</h2>
                    <table>
                        <tr>
                            <th width="300px">Товар</th>
                            <th width="80px">Цена</th>
                            <th width="80px">Actions</th>
                        </tr>
                        {% for p in prod %}
                        <tr>
                            <td>
                                <div class="bottom1-line1">
                                    <img src="{{ p.logo_image.url }}" alt="{{ p.title }}" width="72px" height="72px" aria-colcount="#475156">
                                    <p>{{ p.title }}</p>
                                </div>
                            </td>
                            <td >{{ p.price }} ₽</td>
                            <td class="actions">
                                {% if p.count_in_cart %}
                                <a href="{% url 'cart_decr_in_index' product_id=p.id %}"><button>-</button></a>
                                {{ p.count_in_cart }}
                                <a href="{% url 'cart_add' product_id=p.id %}"><button>+</button></a>
                                {% else %}
                                    <a href="{% url 'cart_add' product_id=p.id %}">
                                    <button>В корзину</button>
                                    </a>
                                {% endif %}

                                <a href="{% url 'rem_fav' product_id=p.id %}"><button1 class="actions button1">
                                    <img src="{% static 'chipi/images/del.png' %}" width="24px" height="24px">
                                </button1></a>
                            </td>
                        </tr>
                        {% endfor %}


                    </table>
            </div>
        </div>
    {% else %}
        <div>
        <link rel="stylesheet" href="style-favorite.css">

                <div class="container">
                    <h2>Список желаемого пуст</h2>

            </div>
        </div>
    {% endif %}

{% endblock %}

market/chipi/templates/chipi/index.html
{% extends 'base.html' %}

{% block content %}

    {% for p in prod %}
    <p><b>{{ p.title }}</b></p>
    <p>{{ p.price }}₽</p>
    <a href="{{ p.get_absolute_url }}">click</a>

    <p>shop:<a href="{{ p.shop.get_absolute_url }}">{{ p.shop.name }}</a> </p>
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
{% endblock %}

market/chipi/templates/chipi/orders_shop.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'chipi/css/order.css' %}">


<div>
		<link rel="stylesheet" href="style-history.css">
        <div class="t">
            <div class="panel">
                <div class="panel-1">
                    <img class="panel-1-img" src="{% static 'chipi/images/Storefront1.svg' %}" alt="2">
                    <a href="{% url 'orders' %}"><p class="panel-1-p">История заказов</p></a>
                </div>
                <div class="panel-2">
                    <img class="panel-2-img" src="{% static 'chipi/images/Notebook1.svg' %}" alt="7">
                    <a href="{% url 'users:address' %}"><p class="panel-2-p">Карты и адреса</p></a>
                </div>
                <div class="panel-2">
                    <img class="panel-2-img" src="{% static 'chipi/images/Stack1.svg' %}" alt="1">
                    <a href="{% url 'users:profile' %}"><p class="panel-2-p">Аккаунт</p></a>
                </div>

                <div class="panel-2">
                    <img class="panel-2-img" src="{% static 'chipi/images/ShoppingCartSimple1.svg' %}" alt="4">
                    <a href="{% url 'cart' %}"><p class="panel-2-p">Корзина</p></a>
                </div>
                <div class="panel-2">
                    <img class="panel-2-img" src="{% static 'chipi/images/Heart1.svg' %}" alt="5">
                    <a href="{% url 'favorites' %}"><p class="panel-2-p">Список желаний</p></a>
                </div>
                <div class="panel-2">
                    <img class="panel-2-img" src="{% static 'chipi/images/ArrowsCounterClockwise1.svg' %}" alt="6">
                    <a href="{% url 'users:password_change' %}"><p class="panel-2-p">Сменить пароль</p></a>
                </div>

                <div class="panel-2">
                    <img class="panel-2-img" src="{% static 'chipi/images/Gear1.svg' %}" alt="8">
                    <a href="{% url 'users:profile' %}"><p class="panel-2-p">Настройки</p></a>
                </div>
                <div class="panel-2">
                    <img class="panel-2-img" src="{% static 'chipi/images/SignOut1.svg' %}" alt="9">
                    <a href="{% url 'users:logout' %}"><p class="panel-2-p">Выйти из аккаунта</p></a>
                </div>
            </div>
            <div>
                <table class="table2">
                    <thead>
                        <tr>
                          <th>Заказ</th>
                          <th>Статус</th>
                          <th>Дата</th>
                          <th>Цена</th>
                          <th>Детали</th>
                        </tr>
                {% for order in orders %}
                    <tr>
                        <td style="color: #000; ">{{ order.title|truncatechars:20 }}</td>
                        {% if order.get_status_display == 'Доставлен' %}
                        <td style="color: #2DB224;">{{ order.get_status_display|upper }}</td>
                        {% elif order.get_status_display == 'Ожидает выдачи' %}
                        <td style="color: #2DB224;">{{ order.get_status_display|upper }}</td>
                        {% elif order.get_status_display == 'Отменен' %}
                        <td style="color: #EE5858;">{{ order.get_status_display|upper }}</td>
                        {% else %}
                        <td style="color: #FA8232;">{{ order.get_status_display|upper }}</td>
                        {% endif %}

                        <td>{{ order.time_updated }}</td>
                        <td> {{ order.count }} x {{ order.price }} ₽</td>
                        <td style="color: #2DA5F3;"><a style="color: #2DA5F3;" href="{% url 'edit_order' order.id %}">Посмотреть детали</a><img class='img-mini' src="{% static 'chipi/images/image-next-blue.png' %}" alt="image"></td>

                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
	</div>
<br><br><br>

{% endblock %}

market/chipi/templates/chipi/support.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'chipi/css/support.css' %}">

<div class="vopros">
        <div class="vopros1">
            <p class="vopros1-p1">Есть какой-то вопрос?</p>
            <p class="vopros1-p2">Напишите нам</p>
            <p class="vopros1-p2">support@chipi-chipi.ru</p>
<!--            <div class="vopros11">-->
<!--                <img class='vopros1-img1' src="{% static 'chipi/images/MagnifyingGlass.svg' %}" alt="">-->
<!--                <input class="vopros1-input" type="text" placeholder="Введите ваш вопрос">-->
<!--                <div class="vopros111">-->
<!--                    <button class='vopros1-btn' type="submit">-->
<!--                        <p class="vopros1-p3">ПОДТВЕРДИТЬ</p>-->
<!--                    </button>-->
<!--                </div>-->
<!--            </div>-->
        </div>
        <div class="vopros2">
            <img class='vopros2-img1' src="{% static 'chipi/images/image 50.svg' %}" alt="">
        </div>
    </div>
    <div class="hr"></div>
    <div class="vopros3">
        <p class="vopros3-p1">Как мы можем помочь вам сегодня?</p>
    </div>
    <div class="vopros4">
        <div class="perenos">
            <a href="{% url 'orders' %}">
                <div class="vopros4-1">
                    <img class="vopros4-img1" src="{% static 'chipi/images/Truck1.svg' %}" alt="">
                    <p class="vopros4-p1">Отследить заказ</p>
                </div>
            </a>
            <a href="{% url 'users:password_change' %}">
                <div class="vopros4-1">
                    <img class="vopros4-img1" src="{% static 'chipi/images/LockOpen.svg' %}" alt="">
                    <p class="vopros4-p1">Поменять пароль</p>
                </div>
            </a>
        </div>
        <div class="perenos">
            <a href="{% url 'users:address' %}">
                <div class="vopros4-1">
                    <img class="vopros4-img1" src="{% static 'chipi/images/CreditCard.svg' %}" alt="">
                    <p class="vopros4-p1">Адресса</p>
                </div>
            </a>
            <a href="{% url 'users:profile' %}">
                <div class="vopros4-1">
                    <img class="vopros4-img1" src="{% static 'chipi/images/User.svg' %}" alt="">
                    <p class="vopros4-p1">Пользователь & аккаунт</p>
                </div>
            </a>
        </div>
    </div>
    <div class="vopros5">
        <div class="perenos">
            <a href="{% url 'favorites' %}">
                <div class="vopros4-1">
                    <img class="vopros4-img1" src="{% static 'chipi/images/Stack.svg' %}" alt="">
                    <p class="vopros4-p1">Список желаний</p>
                </div>
            </a>
            <a href="#">
                <div class="vopros4-1">
                    <img class="vopros4-img1" src="{% static 'chipi/images/Notepad.svg' %}" alt="">
                    <p class="vopros4-p1">Доставка</p>
                </div>
            </a>
        </div>
        <div class="perenos">
            <a href="{% url 'cart' %}">
                <div class="vopros4-1">
                    <img class="vopros4-img1" src="{% static 'chipi/images/CreditCard.svg' %}" alt="">
                    <p class="vopros4-p1">Корзина</p>
                </div>
            </a>
            <a href="{% url 'users:shop_register' %}">
                <div class="vopros4-1">
                    <img class="vopros4-img1" src="{% static 'chipi/images/Storefront.svg' %}" alt="">
                    <p class="vopros4-p1">Продавать на Chipi-Chipi</p>
                </div>
            </a>
        </div>
    </div>
    <div class="hr2"></div>
<!--    <div class="vopros6">-->
<!--        <p class="vopros6-p1">Популярные вопросы</p>-->
<!--    </div>-->
<!--    <div class="vopros7">-->
<!--        <div class="vopros7-1">-->
<!--            <ul>-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="#">Как мне вернуть товар?</a>-->
<!--                </li>-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="#">Как сделать возврат?</a>-->
<!--                </li>-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="#">Как долго длится процесс возврата?</a>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--        <div class="vopros7-1">-->
<!--            <ul class="vopros7-ul">-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="#">Каковы «сроки доставки»?</a>-->
<!--                </li>-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="#">Как изменить способ оплаты?</a>-->
<!--                </li>-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="index-account-registration.html">Как создать новый аккаунт?</a>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--        <div class="vopros7-1">-->
<!--            <ul>-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="#">Ошибка при оплате</a>-->
<!--                </li>-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="#">Как получить заказ?</a>-->
<!--                </li>-->
<!--                <li class="vopros7-li">-->
<!--                    <a class='vopros7-a' href="#">Почему мой заказ отменили?</a>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--    </div>-->
    <div class="vopros8">
        <br>
        <p class="vopros8-1-p1">Связь с нами</p>
        <p class="vopros8-1-p2">Не нашли ответ на свой вопрос?<br>Свяжитесь с нами</p>
        <div class="vopros8-2">
            <div class="vopros8-2-1">
                <div class="vopros8-2-11">
                    <img class="vopros8-2-11-img" src="{% static 'chipi/images/Icon.svg' %}" alt="">
                </div>
                <div class="vopros8-2-12">
                    <p class="vopros8-2-12-p1">Позвоните нам</p>
                    <p class="vopros8-2-12-p2">+79990009900</p>
                    <div class="vopros8-2-123-btn">
                        <button class="vopros8-2-12-btn">
                            <p class="vopros8-2-12-btn-p1">ПОЗВОНИТЬ НАМ</p>
                            <img src="{% static 'chipi/images/ArrowRight.png' %}" alt="">
                        </button>
                    </div>
                </div>
            </div>
            <div class="vopros8-2-2">
                <div class="vopros8-2-11">
                    <img class="vopros8-2-11-img" src="{% static 'chipi/images/Icon1.svg' %}" alt="">
                </div>
                <div class="vopros8-2-12">
                    <p class="vopros8-2-12-p1">Напишите нам</p>
                    <p class="vopros8-2-12-p2">support@chipi-chipi.ru</p>
                    <div class="vopros8-2-123-btn">
                        <button class="vopros8-2-12-btn">
                            <p class="vopros8-2-12-btn-p1">НАПИСАТЬ НАМ</p>
                            <img src="{% static 'chipi/images/ArrowRight.png' %}" alt="">
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}